PRODUCT_VERSION_MAJOR = 1
PRODUCT_VERSION_MINOR = 0
PRODUCT_RELEASE_CODENAME = ABYDOS
include vendor/official_devices/devices.mk

ifeq ($(LINEAGE_VERSION_APPEND_TIME_OF_DAY),true)
    LINEAGE_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    LINEAGE_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

LINEAGE_BUILDTYPE ?= UNOFFICIAL

HALOUI_DEVICE := $(patsubst lineage_%,%,$(TARGET_PRODUCT))

ifneq ($(HALOUI_MAINTAINER),)
ifneq ($(filter $(HALOUI_MAINTAINER),$(HALOUI_MAINTAINERS)),)
ifneq ($(filter $(HALOUI_DEVICE),$(HALOUI_DEVICES)),)
    LINEAGE_BUILDTYPE := OFFICIAL
    BUILD_TYPE_OFFICIAL := true
endif
endif
endif

ifeq ($(TARGET_BUILD_GAPPS), true)
    HALOUI_VARIANT := GMS
else
    HALOUI_VARIANT := VANILLA
endif

LINEAGE_VERSION_SUFFIX := $(LINEAGE_BUILD_DATE)-$(LINEAGE_BUILDTYPE)$(LINEAGE_EXTRAVERSION)-$(HALOUI_VARIANT)-$(LINEAGE_BUILD)

# Internal version
LINEAGE_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(PRODUCT_RELEASE_CODENAME)-$(LINEAGE_VERSION_SUFFIX)

# Display version
LINEAGE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(LINEAGE_VERSION_SUFFIX)

# LineageOS version properties
PRODUCT_PRODUCT_PROPERTIES += \
    ro.lineage.version=$(LINEAGE_VERSION) \
    ro.lineage.display.version=$(LINEAGE_DISPLAY_VERSION) \
    ro.lineage.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.lineage.releasetype=$(LINEAGE_BUILDTYPE) \
    ro.haloui.variant=$(HALOUI_VARIANT) \
    ro.haloui.maintainer=$(HALOUI_MAINTAINER)
